"""Curated agent outputs for demo incidents when workflow stages are partial."""

from __future__ import annotations

from typing import Any

DEMO_AGENT_OUTPUTS: dict[str, dict[str, Any]] = {
    "Suspicious PowerShell Execution": {
        "threat_intel": [
            {
                "indicator": "185.234.72.19",
                "indicator_type": "IPv4",
                "reputation": "Malicious",
                "confidence": 88,
                "source": "FALLBACK",
                "description": "Public IPv4 associated with suspicious PowerShell download activity",
                "analyst_notes": "Correlate with encoded command execution on WS-FIN-042.",
            },
            {
                "indicator": "stage.ps1",
                "indicator_type": "URL",
                "reputation": "Suspicious",
                "confidence": 85,
                "source": "FALLBACK",
                "description": "Script staging artifact referenced in PowerShell transcript",
                "analyst_notes": "Quarantine endpoint and block outbound access.",
            },
        ],
        "mitre": [
            {
                "technique_id": "T1059.001",
                "technique_name": "PowerShell",
                "tactic": "Execution",
                "confidence": 92,
                "evidence": ["Encoded PowerShell command", "WINWORD.EXE parent process"],
            },
            {
                "technique_id": "T1105",
                "technique_name": "Ingress Tool Transfer",
                "tactic": "Command and Control",
                "confidence": 85,
                "evidence": ["DownloadString to external IP"],
            },
        ],
        "risk": {
            "overall_risk": "High",
            "risk_score": 78,
            "likelihood": "High",
            "business_impact": "Finance workstation compromise with C2 staging",
            "confidence": 82,
            "priority": "P1",
            "summary": "Active PowerShell execution chain with external network indicators.",
            "reasoning": "Encoded command, suspicious parent process, and outbound connection to untrusted IP.",
        },
        "response": {
            "priority": "P1",
            "containment": [
                "Isolate WS-FIN-042 from the network",
                "Block 185.234.72.19 at perimeter firewall",
            ],
            "eradication": [
                "Remove staged scripts from user profile temp directories",
                "Reset credentials for jsmith",
            ],
            "recovery": [
                "Restore workstation from known-good image after validation",
            ],
            "monitoring": [
                "Hunt for lateral movement across finance VLAN",
            ],
            "executive_summary": "Contain finance workstation and block external C2 before credential reuse.",
        },
        "executive_report": {
            "title": "Suspicious PowerShell Execution — Executive Brief",
            "executive_summary": "PowerShell launched from Microsoft Word with encoded command on a finance workstation.",
            "business_impact": "Potential credential theft and staging for broader compromise in finance department.",
            "markdown_report": "# Incident Report\n\n## Summary\nPowerShell execution from WINWORD.EXE with C2 indicators.\n\n## Actions\nIsolate host, block IP, reset user credentials.",
        },
    },
    "Multiple Failed Login Attempts": {
        "threat_intel": [
            {
                "indicator": "203.0.113.44",
                "indicator_type": "IPv4",
                "reputation": "Suspicious",
                "confidence": 86,
                "source": "FALLBACK",
                "description": "External source of sustained authentication failures",
                "analyst_notes": "Likely password spraying against domain accounts.",
            },
        ],
        "mitre": [
            {
                "technique_id": "T1110.001",
                "technique_name": "Password Guessing",
                "tactic": "Credential Access",
                "confidence": 90,
                "evidence": ["150+ failed logons in 5 minutes"],
            },
        ],
        "risk": {
            "overall_risk": "Medium",
            "risk_score": 62,
            "likelihood": "Medium",
            "business_impact": "Domain account lockout and potential credential compromise",
            "confidence": 80,
            "priority": "P2",
            "summary": "Sustained brute force activity from single external IP.",
            "reasoning": "Volume and rate of failed logons exceed normal thresholds.",
        },
        "response": {
            "priority": "P2",
            "containment": ["Block 203.0.113.44 at firewall", "Enable geo-blocking for auth endpoints"],
            "eradication": ["Review locked accounts for successful logons"],
            "recovery": ["Re-enable accounts after password reset"],
            "monitoring": ["Alert on >50 failures per IP per hour"],
            "executive_summary": "Block external attacker IP and review domain authentication logs.",
        },
        "executive_report": {
            "title": "Brute Force Attack — Executive Brief",
            "executive_summary": "External IP attempted 150+ failed logins against domain accounts.",
            "business_impact": "Risk of account compromise and service disruption from lockouts.",
            "markdown_report": "# Brute Force Incident\n\nBlock source IP and enforce MFA on privileged accounts.",
        },
    },
    "Possible Ransomware Activity": {
        "threat_intel": [
            {
                "indicator": "198.51.100.77",
                "indicator_type": "IPv4",
                "reputation": "Malicious",
                "confidence": 91,
                "source": "FALLBACK",
                "description": "C2 communication from encryption process",
                "analyst_notes": "Observed beaconing during mass file encryption.",
            },
        ],
        "mitre": [
            {
                "technique_id": "T1486",
                "technique_name": "Data Encrypted for Impact",
                "tactic": "Impact",
                "confidence": 96,
                "evidence": ["Mass file extension change to .locked"],
            },
            {
                "technique_id": "T1490",
                "technique_name": "Inhibit System Recovery",
                "tactic": "Impact",
                "confidence": 94,
                "evidence": ["Volume shadow copy deletion"],
            },
        ],
        "risk": {
            "overall_risk": "Critical",
            "risk_score": 95,
            "likelihood": "High",
            "business_impact": "Finance file server encryption and operational outage",
            "confidence": 94,
            "priority": "P1",
            "summary": "Active ransomware behavior with shadow copy deletion.",
            "reasoning": "Mass encryption, ransom note creation, and C2 beacons confirmed.",
        },
        "response": {
            "priority": "P1",
            "containment": ["Isolate FS-PROD-01 and WS-HR-017 immediately"],
            "eradication": ["Remove encrypt.exe and persistence registry keys"],
            "recovery": ["Restore from offline backups after forensics"],
            "monitoring": ["Scan entire estate for .locked extension artifacts"],
            "executive_summary": "Treat as active ransomware — isolate hosts and initiate recovery playbook.",
        },
        "executive_report": {
            "title": "Ransomware Activity — Executive Brief",
            "executive_summary": "Critical ransomware encryption detected on finance file server.",
            "business_impact": "Finance operations disrupted; potential data loss without backup restore.",
            "markdown_report": "# Ransomware Incident\n\nIsolate affected hosts and activate disaster recovery.",
        },
    },
    "Credential Dumping via LSASS": {
        "threat_intel": [
            {
                "indicator": "lsass.dmp",
                "indicator_type": "URL",
                "reputation": "Malicious",
                "confidence": 93,
                "source": "FALLBACK",
                "description": "LSASS memory dump artifact on domain controller",
                "analyst_notes": "Classic credential dumping technique requiring immediate response.",
            },
        ],
        "mitre": [
            {
                "technique_id": "T1003.001",
                "technique_name": "LSASS Memory",
                "tactic": "Credential Access",
                "confidence": 95,
                "evidence": ["procdump.exe targeting lsass.exe"],
            },
        ],
        "risk": {
            "overall_risk": "High",
            "risk_score": 88,
            "likelihood": "High",
            "business_impact": "Domain credential exposure from DC compromise",
            "confidence": 90,
            "priority": "P1",
            "summary": "Credential dumping on domain controller.",
            "reasoning": "LSASS dump and Mimikatz-like script block indicate active credential theft.",
        },
        "response": {
            "priority": "P1",
            "containment": ["Isolate DC01 from network", "Disable compromised service accounts"],
            "eradication": ["Delete dump files and investigate procdump origin"],
            "recovery": ["Force domain password reset for tier-0 accounts"],
            "monitoring": ["Monitor for golden ticket and pass-the-hash activity"],
            "executive_summary": "Domain controller credential dump requires tier-0 incident response.",
        },
        "executive_report": {
            "title": "Credential Dumping — Executive Brief",
            "executive_summary": "LSASS memory dump detected on domain controller.",
            "business_impact": "Full domain credential compromise risk.",
            "markdown_report": "# Credential Access Incident\n\nActivate tier-0 IR and reset privileged credentials.",
        },
    },
    "Suspicious Outbound Connection": {
        "threat_intel": [
            {
                "indicator": "45.33.32.156",
                "indicator_type": "IPv4",
                "reputation": "Malicious",
                "confidence": 89,
                "source": "FALLBACK",
                "description": "Beaconing to known malicious IP",
                "analyst_notes": "Periodic outbound connections with high byte volume.",
            },
        ],
        "mitre": [
            {
                "technique_id": "T1071.001",
                "technique_name": "Web Protocols",
                "tactic": "Command and Control",
                "confidence": 87,
                "evidence": ["HTTP beacon every 60 seconds"],
            },
        ],
        "risk": {
            "overall_risk": "High",
            "risk_score": 74,
            "likelihood": "High",
            "business_impact": "Potential data staging on sales workstation",
            "confidence": 83,
            "priority": "P1",
            "summary": "Persistent outbound beacon to malicious IP.",
            "reasoning": "Regular interval connections and firewall reputation match.",
        },
        "response": {
            "priority": "P1",
            "containment": ["Block 45.33.32.156", "Isolate WS-SALES-12"],
            "eradication": ["Collect memory image and remove persistence"],
            "recovery": ["Rebuild workstation after malware check"],
            "monitoring": ["Hunt for same C2 across sales subnet"],
            "executive_summary": "Block C2 IP and isolate sales workstation.",
        },
        "executive_report": {
            "title": "Outbound Beacon — Executive Brief",
            "executive_summary": "Sales workstation beaconing to malicious external IP.",
            "business_impact": "Possible data staging and remote access foothold.",
            "markdown_report": "# C2 Beacon Incident\n\nIsolate endpoint and block malicious IP.",
        },
    },
    "DNS Tunneling Detected": {
        "threat_intel": [
            {
                "indicator": "evil-c2.example.com",
                "indicator_type": "Domain",
                "reputation": "Suspicious",
                "confidence": 84,
                "source": "FALLBACK",
                "description": "High-entropy DNS queries to suspicious subdomain",
                "analyst_notes": "DNS tunneling pattern with abnormal query rate.",
            },
        ],
        "mitre": [
            {
                "technique_id": "T1071.004",
                "technique_name": "DNS",
                "tactic": "Command and Control",
                "confidence": 86,
                "evidence": ["450 DNS queries in 5 minutes", "63-char subdomains"],
            },
        ],
        "risk": {
            "overall_risk": "Medium",
            "risk_score": 68,
            "likelihood": "Medium",
            "business_impact": "Covert data channel from developer workstation",
            "confidence": 78,
            "priority": "P2",
            "summary": "DNS tunneling indicators on development host.",
            "reasoning": "High entropy queries and volume exceed baseline.",
        },
        "response": {
            "priority": "P2",
            "containment": ["Block evil-c2.example.com at DNS sinkhole"],
            "eradication": ["Inspect WS-DEV-03 for tunneling client"],
            "recovery": ["Reimage host if tunneling tool confirmed"],
            "monitoring": ["Enable DNS analytics alerts for entropy spikes"],
            "executive_summary": "Sinkhole suspicious domain and inspect developer workstation.",
        },
        "executive_report": {
            "title": "DNS Tunneling — Executive Brief",
            "executive_summary": "Abnormal DNS queries suggest covert C2 channel.",
            "business_impact": "Potential exfiltration via DNS from dev environment.",
            "markdown_report": "# DNS Tunneling Incident\n\nSinkhole domain and inspect developer host.",
        },
    },
    "Malware Download from CDN": {
        "threat_intel": [
            {
                "indicator": "84c82834a5d2baa474127145eea280a47288179389d56265f74838687532eda",
                "indicator_type": "SHA256",
                "reputation": "Malicious",
                "confidence": 95,
                "source": "FALLBACK",
                "description": "Known ransomware-related hash (WannaCry sample)",
                "analyst_notes": "Sandbox confirmed malicious update.exe.",
            },
        ],
        "mitre": [
            {
                "technique_id": "T1204.002",
                "technique_name": "Malicious File",
                "tactic": "Execution",
                "confidence": 91,
                "evidence": ["update.exe executed after CDN download"],
            },
        ],
        "risk": {
            "overall_risk": "High",
            "risk_score": 80,
            "likelihood": "High",
            "business_impact": "Malware execution on marketing workstation",
            "confidence": 88,
            "priority": "P1",
            "summary": "Confirmed malware download and execution.",
            "reasoning": "Sandbox verdict malicious and hash matches known ransomware family.",
        },
        "response": {
            "priority": "P1",
            "containment": ["Isolate WS-MKT-07", "Block cdn-drop.example.net"],
            "eradication": ["Quarantine update.exe and kill process tree"],
            "recovery": ["Restore from backup after validation"],
            "monitoring": ["Scan for same hash across estate"],
            "executive_summary": "Isolate marketing workstation and block malware CDN.",
        },
        "executive_report": {
            "title": "Malware Download — Executive Brief",
            "executive_summary": "User downloaded and executed malware from CDN.",
            "business_impact": "Active malware on marketing workstation.",
            "markdown_report": "# Malware Incident\n\nIsolate host and block malicious CDN domain.",
        },
    },
    "Lateral Movement via SMB": {
        "threat_intel": [
            {
                "indicator": "10.20.30.5",
                "indicator_type": "IPv4",
                "reputation": "Suspicious",
                "confidence": 82,
                "source": "FALLBACK",
                "description": "Internal host initiating SMB admin sessions",
                "analyst_notes": "Service account used for lateral movement.",
            },
        ],
        "mitre": [
            {
                "technique_id": "T1021.002",
                "technique_name": "SMB/Windows Admin Shares",
                "tactic": "Lateral Movement",
                "confidence": 93,
                "evidence": ["ADMIN$ share access", "PsExec remote execution"],
            },
        ],
        "risk": {
            "overall_risk": "Critical",
            "risk_score": 91,
            "likelihood": "High",
            "business_impact": "Engineering subnet compromise spreading",
            "confidence": 90,
            "priority": "P1",
            "summary": "Active lateral movement across engineering hosts.",
            "reasoning": "SMB admin share use and PsExec from service account.",
        },
        "response": {
            "priority": "P1",
            "containment": ["Disable svc_deploy account", "Segment engineering VLAN"],
            "eradication": ["Remove remote execution tools from targets"],
            "recovery": ["Reset service account credentials"],
            "monitoring": ["Alert on PsExec and ADMIN$ access"],
            "executive_summary": "Disable compromised service account and segment engineering network.",
        },
        "executive_report": {
            "title": "Lateral Movement — Executive Brief",
            "executive_summary": "Service account used for SMB lateral movement in engineering.",
            "business_impact": "Multi-host compromise risk in engineering environment.",
            "markdown_report": "# Lateral Movement Incident\n\nDisable account and segment network.",
        },
    },
    "Privilege Escalation Attempt": {
        "threat_intel": [
            {
                "indicator": "fodhelper.exe",
                "indicator_type": "Hostname",
                "reputation": "Suspicious",
                "confidence": 81,
                "source": "FALLBACK",
                "description": "UAC bypass via fodhelper registry hijack",
                "analyst_notes": "Privilege escalation on HR workstation.",
            },
        ],
        "mitre": [
            {
                "technique_id": "T1548.002",
                "technique_name": "Bypass User Account Control",
                "tactic": "Privilege Escalation",
                "confidence": 88,
                "evidence": ["fodhelper registry hijack", "elevated admin session"],
            },
        ],
        "risk": {
            "overall_risk": "High",
            "risk_score": 76,
            "likelihood": "Medium",
            "business_impact": "HR workstation elevated to admin without approval",
            "confidence": 84,
            "priority": "P1",
            "summary": "UAC bypass elevating HR user privileges.",
            "reasoning": "Registry hijack and new high-integrity session detected.",
        },
        "response": {
            "priority": "P1",
            "containment": ["Isolate WS-HR-04", "Revoke elevated session"],
            "eradication": ["Remove fodhelper registry modifications"],
            "recovery": ["Reset hr_user password and reimage if needed"],
            "monitoring": ["Alert on UAC bypass techniques"],
            "executive_summary": "Isolate HR workstation and revoke elevated access.",
        },
        "executive_report": {
            "title": "Privilege Escalation — Executive Brief",
            "executive_summary": "UAC bypass detected on HR workstation.",
            "business_impact": "Unauthorized admin access on HR systems.",
            "markdown_report": "# Privilege Escalation Incident\n\nIsolate host and reset HR user credentials.",
        },
    },
    "Data Exfiltration to Cloud Storage": {
        "threat_intel": [
            {
                "indicator": "exfil-bucket-xyz",
                "indicator_type": "Domain",
                "reputation": "Malicious",
                "confidence": 92,
                "source": "FALLBACK",
                "description": "Unknown S3 bucket used for large upload",
                "analyst_notes": "500MB financial archive uploaded to external cloud.",
            },
        ],
        "mitre": [
            {
                "technique_id": "T1567.002",
                "technique_name": "Exfiltration to Cloud Storage",
                "tactic": "Exfiltration",
                "confidence": 94,
                "evidence": ["500MB upload to s3.amazonaws.com", "DLP alert on payroll.zip"],
            },
        ],
        "risk": {
            "overall_risk": "Critical",
            "risk_score": 93,
            "likelihood": "High",
            "business_impact": "Financial data exfiltration to external cloud",
            "confidence": 92,
            "priority": "P1",
            "summary": "Large financial archive exfiltrated to unknown S3 bucket.",
            "reasoning": "DLP alert, netflow volume, and cloud upload confirmed.",
        },
        "response": {
            "priority": "P1",
            "containment": ["Block exfil-bucket-xyz S3 bucket", "Isolate WS-FIN-08"],
            "eradication": ["Revoke cloud API keys if misused"],
            "recovery": ["Assess regulatory notification requirements"],
            "monitoring": ["Enhance DLP rules for financial archives"],
            "executive_summary": "Block cloud bucket and assess data breach notification.",
        },
        "executive_report": {
            "title": "Data Exfiltration — Executive Brief",
            "executive_summary": "500MB financial archive uploaded to unknown S3 bucket.",
            "business_impact": "Potential regulatory breach and financial data loss.",
            "markdown_report": "# Data Exfiltration Incident\n\nBlock bucket and initiate breach assessment.",
        },
    },
}

GUARDIAN_AGENTS = (
    "evidence",
    "threat_intelligence",
    "mitre",
    "risk",
    "response",
    "executive_report",
)
